create_task:
  name: Create task
  description: Create a new Charteris task in a specific list, with optional due date, description, and priority.
  fields:
    entry_id:
      required: false
      selector:
        text:
    list_id:
      required: false
      selector:
        text:
    list_name:
      required: false
      selector:
        text:
    title:
      required: true
      selector:
        text:
    description:
      required: false
      selector:
        text:
          multiline: true
    due_date:
      required: false
      selector:
        date:
    priority:
      required: false
      selector:
        number:
          min: 1
          max: 5
          mode: box
